### ISSUE TITLE
getOptions() method in Select class throws exception

### ISSUE THREAD

**Issue by LaVa1804** [WileyLabs/teasy#60] opened 2017-09-08 09:35 UTC

**Comment by BlackEnf0rcer** [comment] 2017-09-12 13:05
I also encountered this bug.

**Comment by vefimofff** [comment] 2017-09-13 06:23
We found the cause of it and it will be fixed in the upcoming release.

**Comment by BlackEnf0rcer** [comment] 2017-09-13 13:17
select.getWrappedWebElement().elements(By.cssSelector("option"));
do the work

**Comment by vefimofff** [comment] 2017-09-13 13:22
@BlackEnf0rcer  yeah, thanks for the suggested workaround. getOptions will be fixed. The entire approach to custom elements will probably be reworked later to be more useful and flexible

**Comment by vefimofff** [comment] 2017-09-14 05:08
Fixed in 1.0.9-beta.

**Closed by vefimofff** 2017-09-14 05:08 UTC
