### ISSUE TITLE
OurWaitFor.absent() fails with TimeOutException / NullPointerException if element is absent in dom

### ISSUE THREAD

**Issue by BlackEnf0rcer** [WileyLabs/teasy#26] opened 2017-07-26 09:27 UTC
In fact method absent wait for invisibility of element. 
Expected behavior that absent() wait for absence of element in dom.
Moreover it's will be great to have an option about waiting for visibility/invisibility with absence of element too.

**Comment by vefimofff** [comment] 2017-07-26 15:00
Hey @BlackEnf0rcer,  interesting idea. Could you please share the real-life case when your test care about the element being "invisible" or "absent in dom"? 
We could discuss it in our gitter chat so others can also share their thoughts, what do you think? 
(please join if u agree - https://gitter.im/teasy-test-framework/Lobby)

**Comment by vefimofff** [comment] 2017-07-28 09:13
Having re-read the comment I suppose I get the suggestion - so we keep the name as "absent" but will check for eithet "absent in dom" or "isDisplayed=false"

**Comment by vefimofff** [comment] 2017-08-25 06:22
@BlackEnf0rcer going back to your suggestion. I have received a comment from another user that it might be confusing that element().should().beAbsent() fails with TimeoutException. But if you take a closer look it is an element() method that actually fails in case there is no element. (because it's expected behavior of an element() method to return only in case of a visible element - otherwise to fail). 
Method absent() will return true (i.e will continue test) if the element (that was present before calling a condition) will become absent in dom (StaleElementException will be thrown by element and caught by absent()).
We have some ideas on how to make element().should().beAbsent() not failing on element() method call but it may take some more time to work it out.

As of now, you can just rework your logic for the absence of an element in a different way. If you need any suggestion on this - please ping me in a gitter chat.

**Comment by vefimofff** [comment] 2017-09-14 05:08
Fixed in 1.0.9-beta.

**Closed by vefimofff** 2017-09-14 05:08 UTC
